[package]
name = "kiss_rss"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = " 0.9.18"
roxmltree = "0.18.0"
dirs = "4.0.0"
chrono = "0.4.23"
