[package]
name = "kiss_rss"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = " 0.9.18"
roxmltree = "0.18.0"
dirs = "4.0.0"
chrono = "0.4.23"
dioxus = { version = "0.3.1", optional = true }
dioxus-desktop = { version = "0.3.0", optional = true }

[features]
build-app = ["dioxus", "dioxus-desktop"]

[[bin]]         
name = "app"    
required-features = ["build-app"] 